#!/bin/sh
dir=`dirname $0`
fs=`df -P . | awk 'NR == 2 {print $NF}'`
mountinfo=`mount | grep "^$fs "`
$dir/bench id "`uname -a`
$mountinfo" verbose disk tree | tee $dir/`hostname`.`date '+%Y-%m-%d:%H:%M:%S'`
