#!/bin/bash
d=`dirname $0`
n=2
s=$1
stop=`date -d '30 minutes' '+%s'`
while true
do
    echo $n
    $d/largedir -l -s "$s" $n >> largedir.out
    [ $? -ne 0 ] && exit
    [ "`date '+%s'`" -gt "$stop" ] && exit
    let n="$n*3/2"
done
