#!/bin/sh 
if [ $# -ne 2 ]
then
    echo "Usage: $0 device file" >&2
    exit 1;
fi
./diskbench $1 > $2
if gnuplot --version | grep '^gnuplot 4' 
then
    gnuplot <<'    EOF'
     set data style dots
     set grid
     set term png size 800,600
     set output "$2.png"
     plot "$2" using 1:4
    EOF
else
    gnuplot <<'    EOF'
     set data style dots
     set grid
     set term png color
     set output "$2.png"
     plot "$2" using 1:4
    EOF
fi

